### ISSUE TITLE
LC mcmc error

### ISSUE THREAD

**Issue by binnietom** [BradGreig/Hybrid21CM#31]
Hi Steven,

Just to let you know, the Light cone mcmc example (from docs/tutorials/) produces the following error (below) when I run it. -I need to rewrite some mpi things anyway so I'll make my own function for now but I thought I'd let you know.
Thanks,
Tom

/home/tab216/anaconda2/envs/hybrid/lib/python3.6/site-packages/powerbox/dft.py:51: UserWarning: You do not have pyFFTW installed. Installing it should give some speed increase.
  warnings.warn("You do not have pyFFTW installed. Installing it should give some speed increase.")
Traceback (most recent call last):
  File "lightcone_tutorial.py", line 47, in <module>
    log_level_stream=logging.DEBUG
  File "/home/tab216/Hybrid21CM/src/py21cmmc/mcmc/mcmc.py", line 147, in run_mcmc
    chain.setup()
  File "/home/tab216/Hybrid21CM/src/py21cmmc/mcmc/cosmoHammer/LikelihoodComputationChain.py", line 163, in setup
    cModule.setup()
  File "/home/tab216/Hybrid21CM/src/py21cmmc/mcmc/likelihood.py", line 420, in setup
    LikelihoodBaseFile.setup(self)
  File "/home/tab216/Hybrid21CM/src/py21cmmc/mcmc/likelihood.py", line 129, in setup
    simctx = self.chain.simulate_mock()
  File "/home/tab216/Hybrid21CM/src/py21cmmc/mcmc/cosmoHammer/LikelihoodComputationChain.py", line 76, in simulate_mock
    core.simulate_mock(ctx)
  File "/home/tab216/Hybrid21CM/src/py21cmmc/mcmc/core.py", line 157, in simulate_mock
    self.build_model_data(ctx)
  File "/home/tab216/Hybrid21CM/src/py21cmmc/mcmc/core.py", line 453, in build_model_data
    write=self.io_options['cache_ionize'],
KeyError: 'cache_ionize'

**Comment by steven-murray** [comment]
Hi Tom,

Yeah, I saw this too. It's actually fixed on the master branch over at https://github.com/21cmfast/21CMMC. I don't know if that helps you at all -- if you want to keep up with the latest version, you should probably use that one.
